language: node_js
node_js:
- '8'
install:
- npm install
before_deploy: npm run dist
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  api_key:
    secure: pHoRyu0QG80pc/kHuNwO5vx255QMkSdbMg8LWKSZ+QIcVNjXHwPnjBB3e9MT/HI0Xw52rTTRA5exbxjwNEPCbZBA2tLcJ67QLgm89/ks2h2RD72jNaZO5Mof0zf4rk5jgcyyyaY/8Lvd7gSF5gVcDcv4DwU5sq2iZOgEjp0aRoyNuuMpioV31eiMPdgbVO9Gzacnu1CAj/0fkebzVppXr7BFthCKyom0AmOkTmQ6BTpTuoEPbu1jjPC+8KmwAxx3qmx42pt4l+G18W7GHTKJFN85SKBSBfECjE46YsJCYIliF+ILw7Ecays1MwH6Lx5J5MaHvSHj6RTZABrhimlENGBLqqWIfuaAhucoYOY3lkJ+gN0wVT/HUCLNNy8rsEUe87b798kjHjJXYHKQXgXEJvuDjak2CqYoRkqP9k93UjfY4BQFK1Gb+hObZaQOjCNQX/sj1+4Jdn38P2W/klNXyYFPbUw5hWW1tewgmUhk+HlLTRtEVoInlBQTtSij+OguTo2s2w81xtYQH0jcBP1N5ixfO0sgilIGVijKJRT3LICQa+n1lJjJz6Xuvt/+/cyWYsIX1dmEM3I9pDbDidLqfWxeU3cUU4S+DnM05SGY2DM0FRGlLd/GhhbWOXaIvXnV908b6naxslwx0bKQrc7x+3UEu4wCc6AYUcNq/yAe+Ok=
  file: dist/*
  on:
    tags: true
    repo: datahq/data-desktop
