language: node_js
node_js:
- '8'
install:
- npm install
before_deploy: npm run dist
deploy:
  provider: releases
  file_glob: true
  file: dist/*
  skip_cleanup: true
  on:
    tags: true
  api_key:
    secure: nyBz6ADMDw2OwqkIx86BL/MDWGtGiyCRm6mmDfxGch1w1xIPuzd+1pvZ79GOzg/gJorezzvxxxgtJiH9azTNLjIjNZtBiBSh7TdmQ+ckMgNn/dPkuM+5MY4JnxeQ0jEeFgBVjpCMVCwOO9OezUtHdlA1orKpCpC0TAEmlxEnUT+fBJ6fRsTbDLkQA4fbXwEYDW7dcpTJ01iGTLiXy2Jx6apt9Q10LH7r7yczYCY/bj7PHPd0S+ILoLiuTOg7qBQldP8IoQe5za2OoB7mRA2ZqNROg0PX4krf/iQQ/LgIGvGVo7ErAD76Ue8P4gq5iLUiWxw+MO2JpWa9tRqOzBd+XR8Ye4DQvIfXHttFxjncLJlAy0y8kC4l4k4idLl+YX1S4VztndOVeP9lUrQaXsIlHHusV8zGlBkSbw+9ghH6XWu/vXgCxHH4rN6Sm07FOCSMV5gVvom5ZuvvOQvd0DoatqRxap9zZFiKOvqgaQM/b2erskJXZfLJWW033ppzzNFtrZsTX5yLhOI+93r2HZeTqDeTP+OkwsUJ3ScTyVZPq3fkEudFPiYwJV3w9MnX8h2d3DpV680bE249KaEtn2Yp1dFsubsSbYz682CIvrjB9uFHAdvKjkEmiJ2mKQ4FTKWK4XmmXpieNPISCwoSdAkOQzovIsLnNaaB4KMLaHaO18I=